### ISSUE TITLE
Найти/создать ассеты героя

### ISSUE THREAD

**Issue by N1k1ko** [SemarglUrFU/Pridie-nito#3]
https://assetstore.unity.com/packages/2d/characters/hero-knight-pixel-art-165188

**Comment by N1k1ko** [comment]
нужны другие

**Comment by N1k1ko** [comment]
как на счёт..?

1. https://assetstore.unity.com/packages/2d/characters/furball-2d-v1-2-mobile-optimized-40588
2. https://assetstore.unity.com/packages/2d/characters/free-pixel-mob-113577

**Comment by KIEC00** [comment]
2й можно использовать как врага, а 1й не очень

**Comment by WaterNate** [comment]
Мои варианты: https://assetstore.unity.com/packages/2d/characters/martial-hero-170422 
 https://assetstore.unity.com/packages/2d/characters/medieval-king-pack-2-174863     https://assetstore.unity.com/packages/2d/characters/warrior-free-asset-195707     https://assetstore.unity.com/packages/2d/characters/bandits-pixel-art-104130
В остальном в магазине юнити ничего приличного почти ничего в пиксельной тематике(голосую за короля, король прикольный)

**Comment by KIEC00** [comment]
Ясно, возьму тяночку :D

**Comment by KIEC00** [comment]
Предлагаю этот вариант: https://assetstore.unity.com/packages/2d/characters/sunny-land-103349

**Comment by N1k1ko** [comment]
лисица принята
