### ISSUE TITLE
Найти/создать ассеты окружения

### ISSUE THREAD

**Issue by N1k1ko** [SemarglUrFU/Pridie-nito#4]
1. https://assetstore.unity.com/packages/2d/environments/2d-platfrom-tile-set-cave-61672
2. https://assetstore.unity.com/packages/2d/environments/platformer-set-150023

**Comment by N1k1ko** [comment]
берём первый

**Comment by KIEC00** [comment]
Предлагаю этот вариант: https://assetstore.unity.com/packages/2d/characters/sunny-land-103349

**Comment by N1k1ko** [comment]
меняем на предложенный
