### ISSUE TITLE
Найти/создать ассеты аудио

### ISSUE THREAD

**Issue by N1k1ko** [SemarglUrFU/Pridie-nito#6]

**Comment by WaterNate** [comment]
1. - https://assetstore.unity.com/packages/audio/music/25-fantasy-rpg-game-tracks-music-pack-240154
2. - https://assetstore.unity.com/packages/audio/music/8bit-music-062022-225623
3. - https://assetstore.unity.com/packages/audio/music/free-music-tracks-for-games-156413
4. - https://assetstore.unity.com/packages/audio/music/electronic/8-bit-fantasy-adventure-music-211334
5. - https://assetstore.unity.com/packages/audio/sound-fx/rpg-orchestral-essentials-music-fx-free-sample-pack-180138
Это фоновая музыка, я голосую за 4-5, но это имхо. Её вроде много и можно поискать ещё, но по большей части она плюс минус одинаковая
Далее звуковые эффекты:
1. - https://assetstore.unity.com/packages/audio/sound-fx/rpg-essentials-sound-effects-free-227708
2. - https://assetstore.unity.com/packages/audio/sound-fx/8-bits-elements-16848
Напряжённая музыка для подземелья босса-которого-нет и для души:
https://assetstore.unity.com/packages/audio/sound-fx/free-spectral-lofi-impacts-198119
