### ISSUE TITLE
Найти/создать элементы GUI и лого

### ISSUE THREAD

**Issue by N1k1ko** [SemarglUrFU/Pridie-nito#7]

**Comment by WaterNate** [comment]
Всё что откопал по gui
1. - https://assetstore.unity.com/packages/2d/gui/icons/royal-ui-volume-1-2-and-3-133347
2. - https://assetstore.unity.com/packages/2d/gui/fantasy-wooden-gui-free-103811
3. - (что-то для полноценных рпг, но можно свиснуть загрузочный экран) https://assetstore.unity.com/packages/2d/gui/simple-fantasy-gui-99451
4. - (каменная тематика, много кнопочек) https://assetstore.unity.com/packages/2d/gui/icons/stone-ui-182526
5. - (курсорчик) https://assetstore.unity.com/packages/2d/gui/icons/fantasy-rpg-cursor-pack-87154

**Comment by KIEC00** [comment]
Мне второй пока что нравится, а загрузочник вряд ли понадобится.
